version: '3.8'

services:
  pvz_service:
    build: .
    ports:
      - "8080:8080"
      - "9000:9000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    volumes:
      - .:/app
    working_dir: /app
