version: '3.8'

services:
  pvz_service:
    build: .
    ports:
      - "8080:8080"
      - "9000:9000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    volumes:
      - .:/app
    working_dir: /app
    command: "uvicorn myapp.app:app --host 0.0.0.0 --port 8080"

  tests:
    build: .
    depends_on:
      - pvz_service
    volumes:
      - .:/app
    working_dir: /app
    command: "pytest tests/"
